### ISSUE TITLE
Accuracy test output

### ISSUE THREAD

**Issue by vgvreug** [alimousavi1997/RecommSys#12]
For your accuracy test the output should probably be the relative error between the two systems, not the results of Recall@10 for each system since the relative error is what you're actually interested in.

**Comment by alimousavi1997** [comment]
Thanks, but I think I have already mentioned it in my doc: " ...I deem a relative error of approximately 50 percent to be within
an acceptable range for comparison purposes."

**Comment by vgvreug** [comment]
Yes, I did see that. I was referring to section 3.2.1 where you describe your accuracy test in more detail. There, the output/result is listed as "Recall@10 for Movie Recommender and Recall@10 for the TFRS". I believe that the actual result of interest is the percent relative error, not the individual results. Apologies if that wasn't clear.

**Comment by alimousavi1997** [comment]
Revised.
