### ISSUE TITLE
Potential error in 3.1.2 of VnV

### ISSUE THREAD

**Issue by vgvreug** [alimousavi1997/RecommSys#13]
In the matrix, you point to the second and third users as the ones that are similar to the last user. However, the second to last user is more similar to the last user than the second user. They (and user 3) have feedback vectors that start [1,2,3,1] whereas user 2 has [1,2,3,2]. Is there a reason the second user is pointed out as being similar instead of the second to last?

**Comment by alimousavi1997** [comment]
Thanks Valerie, but I couldn't get your point. Typically I need more than one user to make some recommendations using Collaborativ filtering. Except user2 and user3, the rest have very different vectors.

**Comment by vgvreug** [comment]
I understand needing multiple users to make a recommendation. The part I'm confused on is why you're using user2 instead of user7. 
user2: 1 2 3 **2** 2 1 5 5
user3: 1 2 3 1 2 2 4 5
user7: 1 2 3 1 2 4 5 4
userT: 1 2 3 1

2, 3, 7, and target all have the same first three ratings, but user 2 has a different fourth rating than the other three. Doesn't that mean that user7 is more similar to the target than user2 and therefore you should use users 3 and 7 to make the recommendation instead of 3 and 2?

**Comment by alimousavi1997** [comment]
Revised.
