### ISSUE TITLE
VnV: Undefined terms

### ISSUE THREAD

**Issue by vgvreug** [alimousavi1997/RecommSys#14]
In the summary section, you use the terms ANN and KNN but don't define them anywhere. It may be that your intended readers would automatically know what those are, but you may want to define or at least write out the full term at least once so people (like me) who aren't familiar have some idea of what you're talking about.

**Comment by alimousavi1997** [comment]
Thanks. Modified.

**Comment by alimousavi1997** [comment]
Revised.
