### ISSUE TITLE
VnV misc issues

### ISSUE THREAD

**Issue by vgvreug** [alimousavi1997/RecommSys#16]
- [x] Summary: "(target user index)" not necessary 
- [x] Summary: "so-called" not necessary
- [x] Summary: "columns represent items indices" <- items should be singular
- [x] Objectives: Maintainability should not be capitalized
- [x] Relevant documentation: Either "The document will reference" or "The reader ... will be referred to"

**Comment by alimousavi1997** [comment]
Thanks. I modified it accordingly.

**Comment by alimousavi1997** [comment]
Revised.
