### ISSUE TITLE
MG+MIS Review

### ISSUE THREAD

**Issue by alimousavi1997** [alimousavi1997/RecommSys#17]
Hello Dr. Smith. Please review my MG and MIS documents.
[MG](https://github.com/alimousavi1997/RecommSys/blob/main/docs/Design/SoftArchitecture/MG.pdf)
[MIS](https://github.com/alimousavi1997/RecommSys/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by smiths** [comment]
[AliMG.pdf - PDF Expert.pdf](https://github.com/alimousavi1997/RecommSys/files/14846214/AliMG.pdf.-.PDF.Expert.pdf)
[AliMIS.pdf - PDF Expert.pdf](https://github.com/alimousavi1997/RecommSys/files/14846215/AliMIS.pdf.-.PDF.Expert.pdf)
