### ISSUE TITLE
MG + MIS Review for Domain Expert 

### ISSUE THREAD

**Issue by alimousavi1997** [alimousavi1997/RecommSys#18]
Hi Nada. Please Review my MG+MIS docs.
[MG](https://github.com/alimousavi1997/RecommSys/blob/main/docs/Design/SoftArchitecture/MG.pdf)
[MIS](https://github.com/alimousavi1997/RecommSys/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by NadaElmasry** [comment]
Hi Ali,
I've provided some feedback for the MG and MIS plans in the following issues #21, #22, #23.
Thank you!
