### ISSUE TITLE
My Problem Statement is Complete

### ISSUE THREAD

**Issue by alimousavi1997** [alimousavi1997/RecommSys#2]
Hello Dr. Smith,
Please review my problem statement

Ali

**Comment by smiths** [comment]
Feedback:

- please include a link to your problem statement for ease of review
- I would like to see equations in your problem statement
- include citations in your problem statement
- the environment isn't Python, the environment is the operating systems on which your software should run.  Python is an implementation choice that you don't have to make at this stage

The project sounds interesting.  We just need to make sure that it is about the computation first and the appearance of the application second.

Your project is approved.
