### ISSUE TITLE
MIS Plan - Item Selector and KNN Modules Exceptions

### ISSUE THREAD

**Issue by NadaElmasry** [alimousavi1997/RecommSys#23]
It seems like both the Item Selector and KNN modules do not have any exceptions. There should be at least an exception to cover incorrect input formats and empty arrays. Depending on the implementation, there can be additional exceptions if the module crashes to provide some explanation of the reason for module failure.

**Comment by alimousavi1997** [comment]
Revised.

**Comment by alimousavi1997** [comment]
Revised.
