### ISSUE TITLE
SRS REview

### ISSUE THREAD

**Issue by alimousavi1997** [alimousavi1997/RecommSys#3]
Hi Dr. Smith. Please review my SRS document

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[AliMousavi_SRS.pdf](https://github.com/alimousavi1997/RecommSys/files/14390307/AliMousavi_SRS.pdf)
