### ISSUE TITLE
SRS Review

### ISSUE THREAD

**Issue by alimousavi1997** [alimousavi1997/RecommSys#4]
Hi Xinyu. Please review my SRS document

**Comment by lele0007** [comment]
I write some comments on the document. 
[SRS-Secondary review.pdf](https://github.com/alimousavi1997/RecommSys/files/14271108/SRS-Secondary.review.pdf)

**Comment by smiths** [comment]
The review is complete, so this issue can be closed.  @alimousavi1997 you should address the feedback from @lele0007.  You may wish to create issues related to specific items of the feedback.
