### ISSUE TITLE
SRS Review

### ISSUE THREAD

**Issue by alimousavi1997** [alimousavi1997/RecommSys#5]
Hi Nada. Please Review my SRS document.
Thanks

**Comment by smiths** [comment]
@NadaElmasry please provide the review of the SRS.

**Comment by NadaElmasry** [comment]
Hi Ali, I apologize for the delayed response. Overall, your document is clear and well-written.
I have made some suggestions in the issues [#8](https://github.com/alimousavi1997/RecommSys/issues/8), [#9](https://github.com/alimousavi1997/RecommSys/issues/9), and [#10](https://github.com/alimousavi1997/RecommSys/issues/10). Please have a look at them when you get a chance. 
Thank you!
