### ISSUE TITLE
VnV Review for Domain Expert Nada Elmasry

### ISSUE THREAD

**Issue by alimousavi1997** [alimousavi1997/RecommSys#7]
Please review my VnVPlan.
[VnVPlan](https://github.com/alimousavi1997/RecommSys/blob/main/docs/VnVPlan/VnVPlan.pdf)

**Comment by NadaElmasry** [comment]
Hi Ali, 
I've provided some feedback for your VnV plan in the following issues #19, #20.
Thank you!
